# Site settings
title: PaintedMonk
email: caius.howcroft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog of caius howcroft, covering cloud computing, food and kids.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: caiushowcroft
github_username:  caisuh

# Build settings
markdown: kramdown
